data:
  data_dir: /media/zzy/Data/PC_Denoise/code/hdd/SonarDiff/HEU_Data/unity
  dataloader: Sonar
  dataset_norm: false
  max_range: 100.0
  num_points: 40000
  resolution: 0.1
  seq_num: 2
  split: train
  std_axis_norm: false
diff:
  beta_end: 0.007
  beta_func: linear
  beta_start: 3.5e-05
  reg_weight: 5.0
  s_steps: 50
  t_steps: 1000
experiment:
  id: 'Ours_add_current_past'
model:
  out_dim: 96
train:
  batch_size: 1
  decay_lr: 0.0001
  lr: 0.001
  max_epoch: 100
  n_gpus: 1
  num_workers: 0
  uncond_prob: 0.1
  uncond_w: 6.0
